# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build core
      run: ./gradlew core:build
    - name: Build backend
      run: ./gradlew clean backend:build
    - name: Build WebUI
      run: ./gradlew clean :webui:html:dist
    - name: Push files onto server
      uses: crykn/copy_folder_to_another_repo_action@v1.0.5b
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: '$GITHUB_WORKSPACE/gdx-setup/gdx-setup/webui/html/build/dist'
        destination_repo: 'crykn/test'
        destination_folder: 'setup'
        destination_branch: 'main'
        user_email: 'crykn@users.noreply.github.com'
        user_name: 'crykn'


